name: Purge cache in Cloudflare
on:
  push:
    branches:
      - "main"
    paths:
      - "*/static/**"
jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cloudflare Purge Cache
        run: |
          curl -XPOST "https://api.cloudflare.com/client/v4/zones/${{ secrets.ZONE_ID }}/purge_cache" \
            -H "authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -H "content-type: application/json" -d '{"purge_everything":true}'
